# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Kristin Fasiang
description: Kristin Fasiang, CS+LS PhD Student
baseurl: ""
url: ""
og_image: /assets/Fall2023Picture.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: CV

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: >- 
         kfasiang@u.northwestern.edu
  follow:
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/kristin-fasiang
    - type: github
      name: GitHub
      link: http://github.com/kfasiang

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
